/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kino.service;

import kino.FilmsService;
import org.junit.Test;
import static org.junit.Assert.*;

public class FilmsServiceTest {
}
